// Actions Constants
export const REQUEST_MOVIE_LIST_ACTIONS = {
  FETCHING: 'REQUEST_MOVIE_LIST_FETCHING',
  SUCCESS: 'REQUEST_MOVIE_LIST_SUCCESS',
  ERROR: 'REQUEST_MOVIE_LIST_ERROR'
}

export const REQUEST_MOVIE_DATA_ACTIONS = {
  FETCHING: 'REQUEST_MOVIE_DATA_FETCHING',
  SUCCESS: 'REQUEST_MOVIE_DATA_SUCCESS',
  ERROR: 'REQUEST_MOVIE_DATA_ERROR'
}

export const MOVIE_LIST_UPDATE_PAGE = 'MOVIE_LIST_UPDATE_PAGE'
