export const GET_POPULAR_MOVIES_IS_LOADING = 'GET_POPULAR_MOVIES_IS_LOADING'
export const GET_POPULAR_MOVIES_HAS_ERROR = 'GET_POPULAR_MOVIES_HAS_ERROR'
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS'

